services:
  django:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: django
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    volumes:
      - ${SRC_PATH}:/root/workspace
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - db_store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: mysqladmin ping
      interval: 15s
      retries: 5

volumes:
  db_store:
